raw_data_config: 
  raw_data_csv: data/raw/data.csv
  model_var: ['0','1','2','3','4','5']
  train_test_split_ratio: 0.2
  target: '6'
  random_state: 111
  name_file : 'column_3C.dat'
  chargement_data : "https://archive.ics.uci.edu/ml/machine-learning-databases/00212/vertebral_column_data.zip"
processed_data_config:
  train_data_csv: data/processed/vetebre_train.csv
  test_data_csv:  data/processed/vetebre_test.csv

model_choice:
  # random_forest or knn
  model: 'knn'
  # model: 'random_forest'

random_forest: 
  max_depth: [15, 30]
  n_estimators: [50, 100]

knn: 
  n_neighbors: [5, 7]
nb_run: 2
mlflow_global_config:
  artifacts_dir: artifacts
  experiment_name: model_vetebre
  registered_model_name: vetebre_model
  remote_server_uri: http://localhost:1234

mlflow_random_forest_config:
  run_name: random_forest
  

mlflow_knn_config:
  run_name: knn
  
model_dir: models/model.joblib

model_webapp_dir: webapp/model_webapp_dir/model.joblib

model_monitor:
  target_col_name: target
  monitor_dashboard_html: reports/data_and_target_drift_dashboard.html
